# Generated by Django 4.1.7 on 2023-03-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDP_table',
            fields=[
                ('type_of_person_FDP', models.CharField(max_length=20)),
                ('name_of_FDP', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('from_date_FDP', models.DateField()),
                ('to_date_FDP', models.DateField()),
                ('organized_by_FDP', models.CharField(max_length=100)),
                ('sponsorship_FDP', models.CharField(max_length=30)),
                ('photo_FDP', models.FileField(upload_to='')),
                ('certificate_FDP', models.FileField(upload_to='')),
            ],
        ),
    ]
