# Generated by Django 4.1.7 on 2023-03-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_profile_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Password_Admin_Profile', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Department', models.CharField(max_length=10)),
                ('Contact_Number', models.IntegerField(max_length=10)),
                ('Faculty_Type', models.CharField(max_length=10)),
                ('Student_Year', models.CharField(max_length=20)),
            ],
        ),
    ]
